import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "react-notion-x/src/styles.css";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body className={`${inter.className} antialiased`}>
        <NextTopLoader color="#2E78C7" showSpinner={false} height={2} />
        <main>{children}</main>
      </body>
    </html>
  );
}
